=== coschtl/brew-controller/brew-controller/src/at/dcosta/brew/recipe/InfusionRecipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="recipe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="malts">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="malt" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" use="optional"/>
                      <xs:attribute type="xs:int" name="amount" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mashing">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="rest" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="temperature" use="optional"/>
                      <xs:attribute type="xs:int" name="time" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="water"/>
            <xs:attribute type="xs:int" name="temperature"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="lautering">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="rest"/>
                <xs:attribute type="xs:int" name="water"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="cooking">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hop" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" />
                      <xs:attribute type="xs:float" name="alpha" />
                      <xs:attribute type="xs:int" name="amount"/>
                      <xs:attribute type="xs:int" name="cookingTime"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="time"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="whirlpool">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="time"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="yeast">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name"/>
                <xs:attribute type="xs:int" name="amount"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name"/>
      <xs:attribute type="xs:string" name="type"/>
      <xs:attribute type="xs:float" name="wort"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== coschtl/brew-controller/brew-controller/src/at/dcosta/brew/recipe/SampleRecipe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- units: -->
<!-- all times are given in minutes -->
<!-- all weights are given in grams -->
<!-- all volumes are given in liters -->
<!-- all temperatures are given in °C -->
<!-- wort is given in °P -->
<recipe  version="1.0" name="SampleBeer" type="infusion" wort="12.3"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="InfusionRecipe.xsd">
	<malts>
		<malt name="Pilsner Malz" amount="2500" />
		<malt name="Pale ale Malz" amount="1500" />
		<malt name="Sauermalz" amount="300" />
	</malts>
	<mashing water="15" temperature="61">
		<rest temperature="67" time="10" />
		<rest temperature="71" time="60" />
		<rest temperature="74" time="0" />
	</mashing>
	<lautering rest="20" water="14" />
	<boiling time="90">
		<hop name="Hopfen 1" alpha="5.3" amount="15" boilingTime="90" />
		<hop name="Hopfen 2" alpha="14" amount="5" boilingTime="70" />
		<hop name="Hopfen 3" alpha="6.8" amount="25" boilingTime="30" />
		<hop name="Hopfen 4" alpha="14" amount="5" boilingTime="0" />
	</boiling>
	<whirlpool time="20" />
	<yeast name="Pilsener Hefe" amount="15" />
</recipe>
